version: "3"
services:

    mysql:
      image: joewt/idocker_mysql:5.7
      container_name: idocker_mysql
      volumes:
        - ${DATA_PATH_HOST}/mysql${MYSQL_VERSION}:/var/lib/mysql
        - ${LOG_PATH_HOST}/mysql${MYSQL_VERSION}:/var/log/mysql
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}

    php-fpm:
      image: joewt/idocker_php-fpm:5.6
      container_name: idocker_php-fpm
      volumes:
       - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
       - ${LOG_PATH_HOST}/php-fpm:/var/log/php-fpm
       - ${LOG_PATH_HOST}/php:/var/log/php
      restart: always

    nginx:
      image: joewt/idocker_nginx:v1
      container_name: idocker_nginx
      depends_on:
       - php-fpm
      volumes:
       - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
       - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
       - ${LOG_PATH_HOST}/nginx:/var/log/nginx
      ports:
       - "80:80"
       - "8081:8081"
      restart: always

    redis:
      image: joewt/idocker_redis:v1
      container_name: idocker_redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "6379:6379"
      restart: always

    phpmyadmin:
      image: joewt/idocker_phpmyadmin:v1
      container_name: idocker_phpmyadmin
      depends_on:
        - mysql
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      ports:
        - "8080:80"
